# Generated by Django 5.2.6 on 2025-10-03 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('dish_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True)),
                ('dish_image', models.ImageField(upload_to='dishes/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
