# Generated by Django 5.2.6 on 2025-10-03 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
